"""add description to products

Revision ID: 36446c0f13a2
Revises: 1bec2ddddce4
Create Date: 2020-11-26 15:47:30.091210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36446c0f13a2'
down_revision = '1bec2ddddce4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'description')
    # ### end Alembic commands ###
